### PR TITLE
Ability to calculate any waypoint (0.5, 0.25, 0.15... of distance)

### PR DESCRIPTION
**Pull request by dimoon**
Ability to calculate any waypoint instead of only midpoint (0.5 of distance).

### CODE REVIEW

**Comment by mnoack** [comment]
@dimoon Whilst I don't like maintaining legacy, I can see some issues if people suddenly upgrade. Maybe you can keep the old methods, and call waypoint with the 0.5 argument to keep it working for existing users.

If you want you could also print a deprecation message if you think we should be getting people to change, but in my opinion midpoint is probably an important enough case to have it's own method.

**Comment by mnoack** [comment]
@dimoon Also for others benefit, what is your use case for it? This could be useful should anyone want to remove this feature in future.

**Comment by dimoon** [comment]
@mnoack do you think `alias_method :midpoint_to, :waypoint_to` will not work properly for this? (I mean legacy code)
As for use case for it. A bit long story :)
I have round track with coordinates of inner and outer border. I need to split distance between two points on ~25cm section for outer border and need to split inner border on the same amount of pieces as for outer(it depends on radius distance, bit for example should be about ~10cm). I need it to be able link position of horse on the track with inner and outer waypoints and display it. I think it's not so unusual task. More fast way to do it is using waypoint calculation with certain shift (distance_factor) instead of midpoints

**Comment by mnoack** [comment]
@dimoon - I think midpoint_between musn't have tests because given the additional required argument it would surely fail those tests, so we really have 2 problems now (backwards compatibility and the existing geokit project lacks tests for what is being changed).

I'm still okay with the idea of the change, just that I believe it will change the behavior of the code an cause someone else's code to break.

**Comment by mnoack** [comment]
I'm closing until we resolve the backwards compatibility question in my last comment. Feel free to re-open when you've resolved that. Thanks for the Pull Request @dimoon

**Pull request closed without merging**
