### PR TITLE
Switch from freegeoip (deprecated) to ipstack

### LINKED ISSUE #215: Support ipstack (old freegeoip.net)
The old freegeoip.net service is deprecated, now accessible at ipstack.com, that requires an API Key. In order to keep it working we need to add a new implementation and notice the deprecation.

> As of March 31 2018 the old freegeoip API is deprecated and a completely re-designed API is now accessible at http://api.ipstack.com. While the new API offers the same capabilities as the old one and also has the option of returning data in the legacy format, the API URL has now changed and all users are required to sign up for a free API Access Key to use the service.

> While we want to keep the disruption to our current users as minimal as possible, we are planning to shut the old API down on July 1st, 2018.

Reference: https://github.com/apilayer/freegeoip#readme

### PR DESCRIPTION
**Pull request by dsantosmerino**
Resolves #215 

(#216 with no extra commits 😄)

### CODE REVIEW

**Comment by dsantosmerino** [comment]
@mnoack It's running with `http` on my local tests, `https` on Travis 😕

**Comment by mnoack** [comment]
Can you delete the cassettes and run them again? I wonder if you ran them before you set the secure flag perhaps. Have a look at the protocol method and see why it's returning https (which relates to the secure variable). It would be interesting to see which condition within that method is returning false when it should return "true" for secure.

**Comment by mnoack** [comment]
That's your call. I prefer if anyone can (for free) run the tests locally and re-generate the cassettes, but I acknowledge that's not possible in all providers (but since it is, let's go with http).

You can also do a http and one https test if you want and it just means someone who changes the implementation can't test the real request for that scenario.

**Comment by mnoack** [comment]
If some of the RIPE ones are failing I'll have to check it out, but my gut says that would be caused by this PR assuming it's passing in master. Sometimes subtle changes (or test ordering affecting state) can do this.

**Comment by dsantosmerino** [comment]
It's working now 😸

**Comment by mnoack** [comment]
@dsantosmerino I've released 1.12 of the gem with this change. Thank You

**Pull request merged**
