### PR TITLE
Make OSMGeocoder host custozimable

### PR DESCRIPTION
**Pull request by dfabreguette**
As we had a Nominatim custom instance, we needed to set a custom API server host (other than https://nominatim.openstreetmap.org/).
I also updated readme. Feel free to tell me if I have anything to change in unit testing...

### CODE REVIEW

**Comment by dfabreguette-ap** [comment]
By the way, we decided to run our own nominatim instance as there were stability issues on main nominatim instance (https://nominatim.openstreetmap.org)...
See the resolved issue for more info https://github.com/openstreetmap/operations/issues/337

**Comment by dfabreguette-ap** [comment]
Hey ! Can this PR be merged please ?

**Comment by dsantosmerino** [comment]
> Hey ! Can this PR be merged please ?

Hey @dfabreguette-ap, thanks for you contribution. It looks legit to me the change. However, can we add small test checking that in effect the host is customizable?

**Comment by ryankopf** [comment]
Closing this PR as it's been two years and no tests provided. If you'd like this to be merged, please ensure that a test specifically covering the change or idea you want is created and that the test passes **rake test**.

**Pull request closed without merging**
