### PR TITLE
fix readme typos

### PR DESCRIPTION
**Pull request by alagram**
Found a few typos while going through the readme. This PR only updates the `README.markdown` file.

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
These are indeed typos. Looks good to me.

**Comment by alagram** [comment]
@olleolleolle thanks for approving! Any idea how I can get this merged please?

**Comment by olleolleolle** [comment]
I have no authority, @dsantosmerino perhaps knows how to get something merged. 🚀

**Comment by dsantosmerino** [comment]
Sorry for the lack of response @alagram. Happy to see your first contribution here.

**Pull request merged**
